version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: side-ticketing-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwer1234!
      POSTGRES_DB: sideticketing
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sideticket-network

volumes:
  postgres-data:

networks:
  sideticket-network:
    driver: bridge
